version: '3'
services:
  oracle-db:
    build:
      context: .
    ports:
      - "1521:1521"
    networks:
      - oracle-network
    container_name: oracle-container

networks:
  oracle-network:
    driver: bridge
